export enum AssetsKeysEnums {
  //gen 1
  BLASTOISE = "BLASTOISE",
  BULBASAUR = "BULBASAUR",
  CHARIZARD = "CHARIZARD",
  CHARMANDER = "CHARMANDER",
  CHARMELEON = "CHARMELEON",
  IVYSAUR = "IVYSAUR",
  SQUIRTLE = "SQUIRTLE",
  VENUSAUR = "VENUSAUR",
  WARTORTLE = "WARTORTLE",
  //gen 2
  CHIKORITA = "CHIKORITA",
  BAYLEEF = "BAYLEEF",
  MEGANIUM = "MEGANIUM",
  TOTODILE = "TOTODILE",
  CROCONAW = "CROCONAW",
  FERALIGATR = "FERALIGATR",
  CYNDAQUIL = "CYNDAQUIL",
  QUILAVA = "QUILAVA",
  TYPHLOSION = "TYPHLOSION",
  //gen 3
  TORCHIC = "TORCHIC",
  COMBUSKEN = "COMBUSKEN",
  BLAZIKEN = "BLAZIKEN",
  MUDKIP = "MUDKIP",
  MARSHTOMP = "MARSHTOMP",
  SWAMPERT = "SWAMPERT",
  TREECKO = "TREECKO",
  GROVYLE = "GROVYLE",
  SCEPTILE = "SCEPTILE",
  //gen 4
  CHIMCHAR = "CHIMCHAR",
  MONFERNO = "MONFERNO",
  INFERNAPE = "INFERNAPE",
  PIPLUP = "PIPLUP",
  PRINPLUP = "PRINPLUP",
  EMPOLEON = "EMPOLEON",
  TURTWIG = "TURTWIG",
  GROTLE = "GROTLE",
  TORTERRA = "TORTERRA",
}

export enum MapKeysEnums {
  BRIDGE_FULLMAP = "BRIDGE_FULLMAP",
  BRIDGE_FOREGROUND = "BRIDGE_FOREGROUND",
  BRIDGE_COLISION = "BRIDGE_COLISION",
  BRIDGE_TILECONFIG = "BRIDGE_TILECONFIG",
}

export enum DataKeysEnums {
  ANIMATIONS = "ANIMATIONS",
}

export enum SceneKeysEnums {
  PRELOAD = "PRELOAD_SCENE",
  BATTLE = "BATTLE_SCENE",
}

export enum AnimationKeysEnums {
  POKEMON_DOWN = "POKEMON_MOVE_DOWN",
  POKEMON_UP = "POKEMON_MOVE_UP",
  POKEMON_LEFT = "POKEMON_MOVE_LEFT",
  POKEMON_RIGHT = "POKEMON_MOVE_RIGHT",
}
