export enum PokemonKeysEnums {
  //gen 1
  BLASTOISE = "BLASTOISE",
  BULBASAUR = "BULBASAUR",
  CHARIZARD = "CHARIZARD",
  CHARMANDER = "CHARMANDER",
  CHARMELEON = "CHARMELEON",
  IVYSAUR = "IVYSAUR",
  SQUIRTLE = "SQUIRTLE",
  VENUSAUR = "VENUSAUR",
  WARTORTLE = "WARTORTLE",
  //gen 2
  CHIKORITA = "CHIKORITA",
  BAYLEEF = "BAYLEEF",
  MEGANIUM = "MEGANIUM",
  TOTODILE = "TOTODILE",
  CROCONAW = "CROCONAW",
  FERALIGATR = "FERALIGATR",
  CYNDAQUIL = "CYNDAQUIL",
  QUILAVA = "QUILAVA",
  TYPHLOSION = "TYPHLOSION",
  //gen 3
  TORCHIC = "TORCHIC",
  COMBUSKEN = "COMBUSKEN",
  BLAZIKEN = "BLAZIKEN",
  MUDKIP = "MUDKIP",
  MARSHTOMP = "MARSHTOMP",
  SWAMPERT = "SWAMPERT",
  TREECKO = "TREECKO",
  GROVYLE = "GROVYLE",
  SCEPTILE = "SCEPTILE",
  //gen 4
  CHIMCHAR = "CHIMCHAR",
  MONFERNO = "MONFERNO",
  INFERNAPE = "INFERNAPE",
  PIPLUP = "PIPLUP",
  PRINPLUP = "PRINPLUP",
  EMPOLEON = "EMPOLEON",
  TURTWIG = "TURTWIG",
  GROTLE = "GROTLE",
  TORTERRA = "TORTERRA",
}

export enum AttacksKeysEnums {
  SCRATCH_1 = "SCRATCH_1",
  SCRATCH_2 = "SCRATCH_2",
  SCRATCH_3 = "SCRATCH_3",
  SCRATCH_4 = "SCRATCH_4",
  SCRATCH_5 = "SCRATCH_5",
}

export enum AbilitiesKeysEnum {
  DASH = "DASH",
}

export enum MapKeysEnums {
  TILESET = "TILESET",
  MAPCONFIG = "MAPCONFIG",
}

export enum DataKeysEnums {
  ATTACK_ANIMATIONS = "ATTACK_ANIMATIONS",
  POKEMON_WALKING_ANIMATIONS = "POKEMON_WALKING_ANIMATIONS",
  POKEMON_SELECTION_ANIMATIONS = "POKEMON_SELECTION_ANIMATIONS",
}

export enum SceneKeysEnums {
  PRELOAD = "PRELOAD_SCENE",
  BATTLE = "BATTLE_SCENE",
  BATTLE_HUD = "BATTLE_HUD_SCENE",
  SELECTION = "SELECTION_SCENE",
}

export enum AnimationKeysEnums {
  POKEMON_DOWN = "POKEMON_MOVE_DOWN",
  POKEMON_UP = "POKEMON_MOVE_UP",
  POKEMON_LEFT = "POKEMON_MOVE_LEFT",
  POKEMON_RIGHT = "POKEMON_MOVE_RIGHT",
}

export enum SFXKeysEnums {
  SELECT = "SELECT",
  CONFIRM = "CONFIRM",
}

export type PokemonStatus = {
  HP: number;
  ATTACK: number;
  SP_ATTACK: number;
  DEFENSE: number;
  SP_DEFENSE: number;
  SPEED: number;
};

export enum AttackTypesEnum {
  PHYSICAL = "PHYSICAL",
  SPECIAL = "SPECIAL",
}

export enum DepthEnum {
  BACKGROUND = 0,
  DASH = 5,
  FOREGROUND = 99,
  COLLISION = 1,
  PLAYER = 5,
  ATTACK = 6,
}
